version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: friday
    timezone: Europe/London
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sharp
    versions:
    - 0.28.0
